[package]
name = "stabil-api"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version = "0.11", features = ["cookies", "multipart"]}
scraper = "0.14.0"
rocket = { version = "=0.5.0-rc.2", default-features = false, features = ["json"] }
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
chrono = "0.4.23"
rocket_okapi = { version = "0.8.0-rc.2", features = ["swagger", "rapidoc"] }
schemars = "0.8.10"
