[package]
name = "stabil-api"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[[bin]]
name = "stabil-api"

[features]
default = ["server"]
server = ["tokio", "axum/http1", "axum/http2", "axum/tokio"]
wasm = ["getrandom"]

[dependencies]
reqwest = {version = "0.11.20", features = ["cookies", "multipart"]}
scraper = "0.17.1"
serde = {version = "1.0.188", features = ["derive"]}
serde_json = "1.0.107"
chrono = "0.4.31"
phf = { version = "0.11.2", features = ["macros"] }
axum = { version = "0.7.5", default-features = false, features = ["json", "query"] }
axum-macros = "0.4.1"
serde_with = "3.7.0"
worker-macros = { version = "0.1.0", default-features = false }
worker = { version = "0.1.0", default-features = false }
getrandom = { version = "0.2.14", features = ["js"], optional = true }
tokio = { version = "1.37.0", features = ["full"], optional = true }
utoipa-swagger-ui = { version = "6.0.0", features = ["axum"] }
utoipa = { version = "4.2.0", features = ["axum_extras"] }
