on:
  push:
    branches:
    - main
  pull_request:

name: Continuous integration

jobs:
  fmt:
    name: cargo fmt
    runs-on: codeberg-small
    steps:
      - name: Check out repository
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Install rust toolchain
        uses: https://github.com/dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: cargo fmt
        continue-on-error: true
        run: cargo fmt --all -- --check

  clippy:
    name: cargo clippy
    runs-on: codeberg-small
    steps:
      - name: Check out repository
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Install rust toolchain
        uses: https://github.com/dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: cargo clippy
        continue-on-error: true
        run: cargo clippy -- -D warnings

  test:
    name: cargo test
    runs-on: codeberg-small
    steps:
      - name: Check out repository
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Install rust toolchain
        uses: https://github.com/dtolnay/rust-toolchain@stable

      - name: cargo check
        run: cargo check

      - name: cargo test
        env:
          STABIL_API_TEST_USERNAME: ${{ secrets.STABIL_API_TEST_USERNAME }}
          STABIL_API_TEST_PASSWORD: ${{ secrets.STABIL_API_TEST_PASSWORD }}
        run: cargo test -q
